// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"server/app/user/cmd/rpc/internal/logic"
	"server/app/user/cmd/rpc/internal/svc"
	"server/app/user/cmd/rpc/pb"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) GetUserInfoById(ctx context.Context, in *pb.UserInfoReq) (*pb.UserInfoReply, error) {
	l := logic.NewGetUserInfoByIdLogic(ctx, s.svcCtx)
	return l.GetUserInfoById(in)
}
