// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	base "server/app/system/cmd/api/internal/handler/base"
	user "server/app/system/cmd/api/internal/handler/user"
	"server/app/system/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/captcha",
				Handler: base.CaptchaHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/file/upload",
				Handler: base.UploadHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: base.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/system/base"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/health",
					Handler: user.HealthHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/system/user"),
	)
}
