// Code generated by goctl. DO NOT EDIT.
package types

type NilReq struct {
}

type NilReply struct {
}

type HealthReply struct {
	Message string `json:"message"`
}

type UserInfoReq struct {
	UserID string `json:"userId"`
}

type UserInfoReply struct {
	UserID string `json:"userId"`
}
