// Code generated by goctl. DO NOT EDIT.
package types

type NilReq struct {
}

type NilReply struct {
}

type HealthReply struct {
	Message string `json:"message"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginReply struct {
	Token string `json:"token"`
	User  User   `json:"user"`
}

type User struct {
	ID        int64  `json:"id"`
	Username  string `json:"username"`
	UUID      string `json:"uuid"`
	Nickname  string `json:"nickname"`
	Email     string `json:"email"`
	Avatar    string `json:"avatar"`
	Role      int64  `json:"role"`
	CreatedAt int64  `json:"createdAt"`
}

type CreateReq struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Nickname string `json:"nickname"`
	Password string `json:"password"`
	Avatar   string `json:"avatar"`
	Role     int64  `json:"role"`
}

type IdReq struct {
	Id int64 `json:"id"`
}

type UserReply struct {
	User User `json:"user"`
}

type PageReq struct {
	Page     int64  `json:"page"`
	PageSize int64  `json:"pageSize"`
	KeyWord  string `json:"keyWord"`
}

type ListReply struct {
	Page     int64  `json:"page"`
	PageSize int64  `json:"pageSize"`
	Total    int64  `json:"total"`
	List     []User `json:"list"`
}

type UpdateReq struct {
	ID       int64  `json:"ID"`
	Username string `json:"username"`
	Email    string `json:"email"`
	Nickname string `json:"nickname"`
	Password string `json:"password"`
	Avatar   string `json:"avatar"`
	Role     int64  `json:"role"`
	Status   int64  `json:"status"`
}

type Business struct {
	BusinessID string `json:"businessId"`
	UUID       string `json:"uuid"`
	Name       string `json:"name"`
	Detail     string `json:"detail"`
	Score      int64  `json:"score"`
	Image      string `json:"image"`
	Status     int64  `json:"status"`
	CreatedAt  int64  `json:"createdAt"`
	UpdatedAt  int64  `json:"updatedAt"`
}

type CreateBusinessReq struct {
	Name     string `json:"name"`
	Detail   string `json:"detail"`
	Image    string `json:"image"`
	Username string `json:"username"`
	Role     int64  `json:"role"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Nil struct {
}
