// Code generated by goctl. DO NOT EDIT.
// Source: log.proto

package server

import (
	"context"

	"server/app/log/cmd/rpc/internal/logic"
	"server/app/log/cmd/rpc/internal/svc"
	"server/app/log/cmd/rpc/pb"
)

type LogServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedLogServer
}

func NewLogServer(svcCtx *svc.ServiceContext) *LogServer {
	return &LogServer{
		svcCtx: svcCtx,
	}
}

func (s *LogServer) LogCreate(ctx context.Context, in *pb.LogCreateReq) (*pb.LogNil, error) {
	l := logic.NewLogCreateLogic(ctx, s.svcCtx)
	return l.LogCreate(in)
}

func (s *LogServer) LogPageList(ctx context.Context, in *pb.LogPageListReq) (*pb.LogPageListReply, error) {
	l := logic.NewLogPageListLogic(ctx, s.svcCtx)
	return l.LogPageList(in)
}
