// Code generated by goctl. DO NOT EDIT.
// Source: cart.proto

package cart

import (
	"context"

	"server/app/cart/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CartNil = pb.CartNil

	Cart interface {
		CartCreate(ctx context.Context, in *CartNil, opts ...grpc.CallOption) (*CartNil, error)
	}

	defaultCart struct {
		cli zrpc.Client
	}
)

func NewCart(cli zrpc.Client) Cart {
	return &defaultCart{
		cli: cli,
	}
}

func (m *defaultCart) CartCreate(ctx context.Context, in *CartNil, opts ...grpc.CallOption) (*CartNil, error) {
	client := pb.NewCartClient(m.cli.Conn())
	return client.CartCreate(ctx, in, opts...)
}
