// Code generated by goctl. DO NOT EDIT.
// Source: product.proto

package server

import (
	"context"

	"server/app/product/cmd/rpc/internal/logic"
	"server/app/product/cmd/rpc/internal/svc"
	"server/app/product/cmd/rpc/pb"
)

type ProductServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedProductServer
}

func NewProductServer(svcCtx *svc.ServiceContext) *ProductServer {
	return &ProductServer{
		svcCtx: svcCtx,
	}
}

func (s *ProductServer) ProductList(ctx context.Context, in *pb.Nil) (*pb.Nil, error) {
	l := logic.NewProductListLogic(ctx, s.svcCtx)
	return l.ProductList(in)
}
