// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	private "server/app/user/cmd/api/internal/handler/private"
	public "server/app/user/cmd/api/internal/handler/public"
	"server/app/user/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/phoneCaptcha",
				Handler: public.PhoneCaptchaHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/registerByPhone",
				Handler: public.UserRegisterByPhoneHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/login/phoneOrUsername",
				Handler: public.UserLoginByPhoneOrUsernameHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/login/phone",
				Handler: public.UserLoginByPhoneHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/user/find",
					Handler: private.UserFindHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/update",
					Handler: private.UserUpdateHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/business/create",
				Handler: public.BusinessCreateHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/business/find",
					Handler: private.BusinessFindHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1"),
	)
}
