// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	private "server/app/order/cmd/api/internal/handler/private"
	"server/app/order/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/order/create",
					Handler: private.OrderCreateHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1"),
	)
}
