// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"

	"github.com/SpectatorNan/gorm-zero/gormc"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"gorm.io/gorm"
)

var (
	cacheApSystemMenuIdPrefix = "cache:apSystem:menu:id:"
)

type (
	menuModel interface {
		Insert(ctx context.Context, tx *gorm.DB, data *Menu) error

		FindOne(ctx context.Context, id int64) (*Menu, error)
		Update(ctx context.Context, tx *gorm.DB, data *Menu) error

		Delete(ctx context.Context, tx *gorm.DB, id int64) error
		Transaction(ctx context.Context, fn func(db *gorm.DB) error) error
	}

	defaultMenuModel struct {
		gormc.CachedConn
		table string
	}

	Menu struct {
		Id        int64          `gorm:"column:id"`
		CreatedAt sql.NullTime   `gorm:"column:created_at"`
		UpdatedAt sql.NullTime   `gorm:"column:updated_at"`
		DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;index"`
		ParentId  int64          `gorm:"column:parent_id"` // 父菜单 id
		Name      string         `gorm:"column:name"`      // 路由name
		Path      string         `gorm:"column:path"`      // 路由path
		Component string         `gorm:"column:component"` // 组件位置对应的前端路径
		Sorted    int64          `gorm:"column:sorted"`    // 排序标记
		Title     string         `gorm:"column:title"`     // 附加属性
		Icon      string         `gorm:"column:icon"`      // 附加属性
	}
)

func (Menu) TableName() string {
	return "`menu`"
}

func newMenuModel(conn *gorm.DB, c cache.CacheConf) *defaultMenuModel {
	return &defaultMenuModel{
		CachedConn: gormc.NewConn(conn, c),
		table:      "`menu`",
	}
}

func (m *defaultMenuModel) Insert(ctx context.Context, tx *gorm.DB, data *Menu) error {

	err := m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(&data).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultMenuModel) FindOne(ctx context.Context, id int64) (*Menu, error) {
	apSystemMenuIdKey := fmt.Sprintf("%s%v", cacheApSystemMenuIdPrefix, id)
	var resp Menu
	err := m.QueryCtx(ctx, &resp, apSystemMenuIdKey, func(conn *gorm.DB, v interface{}) error {
		return conn.Model(&Menu{}).Where("`id` = ?", id).First(&resp).Error
	})
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMenuModel) Update(ctx context.Context, tx *gorm.DB, data *Menu) error {
	old, err := m.FindOne(ctx, data.Id)
	if err != nil && err != ErrNotFound {
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(data).Error
	}, m.getCacheKeys(old)...)
	return err
}

func (m *defaultMenuModel) getCacheKeys(data *Menu) []string {
	if data == nil {
		return []string{}
	}
	apSystemMenuIdKey := fmt.Sprintf("%s%v", cacheApSystemMenuIdPrefix, data.Id)
	cacheKeys := []string{
		apSystemMenuIdKey,
	}
	cacheKeys = append(cacheKeys, m.customCacheKeys(data)...)
	return cacheKeys
}

func (m *defaultMenuModel) Delete(ctx context.Context, tx *gorm.DB, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		if err == ErrNotFound {
			return nil
		}
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Delete(&Menu{}, id).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultMenuModel) Transaction(ctx context.Context, fn func(db *gorm.DB) error) error {
	return m.TransactCtx(ctx, fn)
}

func (m *defaultMenuModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheApSystemMenuIdPrefix, primary)
}

func (m *defaultMenuModel) queryPrimary(conn *gorm.DB, v, primary interface{}) error {
	return conn.Model(&Menu{}).Where("`id` = ?", primary).Take(v).Error
}

func (m *defaultMenuModel) tableName() string {
	return m.table
}
