// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package user

import (
	"context"

	"server/app/user/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateReq     = pb.CreateReq
	Nil           = pb.Nil
	PageReply     = pb.PageReply
	PageReq       = pb.PageReq
	UserIDReq     = pb.UserIDReq
	UserInfoReply = pb.UserInfoReply
	UserReply     = pb.UserReply

	User interface {
		Find(ctx context.Context, in *UserIDReq, opts ...grpc.CallOption) (*UserInfoReply, error)
		List(ctx context.Context, in *PageReq, opts ...grpc.CallOption) (*PageReply, error)
		Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*Nil, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) Find(ctx context.Context, in *UserIDReq, opts ...grpc.CallOption) (*UserInfoReply, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.Find(ctx, in, opts...)
}

func (m *defaultUser) List(ctx context.Context, in *PageReq, opts ...grpc.CallOption) (*PageReply, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.List(ctx, in, opts...)
}

func (m *defaultUser) Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*Nil, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.Create(ctx, in, opts...)
}
