// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package user

import (
	"context"

	"server/app/user/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AdminChangeRoleReq = pb.AdminChangeRoleReq
	CreateReq          = pb.CreateReq
	IDReq              = pb.IDReq
	IDsReq             = pb.IDsReq
	Nil                = pb.Nil
	PageReply          = pb.PageReply
	PageReq            = pb.PageReq
	UUIDReq            = pb.UUIDReq
	UpdateReq          = pb.UpdateReq
	UserInfoReply      = pb.UserInfoReply
	UserLoginReply     = pb.UserLoginReply
	UserLoginReq       = pb.UserLoginReq
	UserReply          = pb.UserReply

	User interface {
		// 用户相关
		UserFind(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*UserInfoReply, error)
		UserList(ctx context.Context, in *PageReq, opts ...grpc.CallOption) (*PageReply, error)
		UserCreate(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*Nil, error)
		UserUpdate(ctx context.Context, in *UpdateReq, opts ...grpc.CallOption) (*Nil, error)
		UserDelete(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*Nil, error)
		UserBatchDelete(ctx context.Context, in *IDsReq, opts ...grpc.CallOption) (*Nil, error)
		Login(ctx context.Context, in *UserLoginReq, opts ...grpc.CallOption) (*UserLoginReply, error)
		UserFindByUUID(ctx context.Context, in *UUIDReq, opts ...grpc.CallOption) (*UserInfoReply, error)
		AdminChangeRole(ctx context.Context, in *AdminChangeRoleReq, opts ...grpc.CallOption) (*Nil, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

// 用户相关
func (m *defaultUser) UserFind(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*UserInfoReply, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.UserFind(ctx, in, opts...)
}

func (m *defaultUser) UserList(ctx context.Context, in *PageReq, opts ...grpc.CallOption) (*PageReply, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.UserList(ctx, in, opts...)
}

func (m *defaultUser) UserCreate(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*Nil, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.UserCreate(ctx, in, opts...)
}

func (m *defaultUser) UserUpdate(ctx context.Context, in *UpdateReq, opts ...grpc.CallOption) (*Nil, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.UserUpdate(ctx, in, opts...)
}

func (m *defaultUser) UserDelete(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*Nil, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.UserDelete(ctx, in, opts...)
}

func (m *defaultUser) UserBatchDelete(ctx context.Context, in *IDsReq, opts ...grpc.CallOption) (*Nil, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.UserBatchDelete(ctx, in, opts...)
}

func (m *defaultUser) Login(ctx context.Context, in *UserLoginReq, opts ...grpc.CallOption) (*UserLoginReply, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultUser) UserFindByUUID(ctx context.Context, in *UUIDReq, opts ...grpc.CallOption) (*UserInfoReply, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.UserFindByUUID(ctx, in, opts...)
}

func (m *defaultUser) AdminChangeRole(ctx context.Context, in *AdminChangeRoleReq, opts ...grpc.CallOption) (*Nil, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.AdminChangeRole(ctx, in, opts...)
}
