version: '3.5'
# 网络配置
networks:
  shop_server:
    driver: bridge

# 服务容器配置
services:
  etcd: # 自定义容器名称
    build:
      context: ./docker-file/etcd                    # 指定构建使用的 Dockerfile 文件
    environment:
      - TZ=Asia/Shanghai
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports: # 设置端口映射
      - "2379:2379"
    networks:
      - shop_server
    restart: always

  etcd-manage:
    build:
      context: ./docker-file/etcd-manage
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "7000:8080"                    # 设置容器8080端口映射指定宿主机端口，用于宿主机访问可视化web
    depends_on: # 依赖容器
      - etcd                                          # 在 etcd 服务容器启动后启动
    networks:
      - shop_server
    restart: always

  user-rpc: # 自定义容器名称
    build:
      context: ./                 # 指定构建使用的 Dockerfile 文件
      dockerfile: app/user/cmd/rpc/Dockerfile
    environment: # 设置环境变量
      - TZ=Asia/Shanghai
    privileged: true
    ports: # 设置端口映射
      - "5551:5551"  # 课件服务rpc端口
    stdin_open: true                     # 打开标准输入，可以接受外部输入
    tty: true
    networks:
      - shop_server
    restart: always                      # 指定容器退出后的重启策略为始终重启

  user-api: # 自定义容器名称
    build:
      context: ./                 # 指定构建使用的 Dockerfile 文件
      dockerfile: app/user/cmd/api/Dockerfile
    environment: # 设置环境变量
      - TZ=Asia/Shanghai
    privileged: true
    ports: # 设置端口映射
      - "5550:5550"  # 课件服务rpc端口
    stdin_open: true                     # 打开标准输入，可以接受外部输入
    tty: true
    networks:
      - shop_server
    restart: always                      # 指定容器退出后的重启策略为始终重启
