// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	private "server/app/product/cmd/api/internal/handler/private"
	public "server/app/product/cmd/api/internal/handler/public"
	"server/app/product/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/product/list",
				Handler: public.ProductListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/product/create",
					Handler: private.ProductCreateHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/category/list",
				Handler: public.CategoryListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/category/create",
					Handler: private.CategoryCreateHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1"),
	)
}
