// Code generated by goctl. DO NOT EDIT.
// Source: order.proto

package order

import (
	"context"

	"server/app/order/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	OrderNil = pb.OrderNil

	Order interface {
		OrderCreate(ctx context.Context, in *OrderNil, opts ...grpc.CallOption) (*OrderNil, error)
	}

	defaultOrder struct {
		cli zrpc.Client
	}
)

func NewOrder(cli zrpc.Client) Order {
	return &defaultOrder{
		cli: cli,
	}
}

func (m *defaultOrder) OrderCreate(ctx context.Context, in *OrderNil, opts ...grpc.CallOption) (*OrderNil, error) {
	client := pb.NewOrderClient(m.cli.Conn())
	return client.OrderCreate(ctx, in, opts...)
}
