Name: product.rpc
ListenOn: 0.0.0.0:6661
Etcd:
  Hosts:
    - 120.77.237.246:32379
  #  - etcd:2379
  Key: product.rpc

Log:
  ServiceName: product-rpc
  Level: info

Mysql:
  Path: 127.0.0.1
  Password: ''
  #  Path: 121.37.20.40
  #  Password: '123456'
  Port: 3306
  Dbname: zero-mall
  Username: root
  MaxIdleConns: 10
  MaxOpenConns: 10
  LogMode: "dev"
  LogZap: false
  Config: charset=utf8mb4&parseTime=True&loc=Local

CRedis:
  Host: '120.77.237.246'
  Port: '6379'
  Password: 'wjh20000905'
  Db: 0